source 'https://rubygems.org'
ruby '3.2.2'

gem 'rails', '~> 7.1.3'
gem 'pg', '~> 1.5'
gem 'puma', '~> 6.4'
gem 'bootsnap', require: false

# Auth
gem 'bcrypt', '~> 3.1.7'
gem 'jwt', '~> 2.7'

# Authorization
gem 'pundit', '~> 2.3'

# Caching / queues / realtime
gem 'redis', '~> 5.0'
gem 'connection_pool', '~> 2.4'
gem 'hiredis-client'
gem 'sidekiq', '~> 7.2'
gem 'sidekiq-cron', '~> 1.12'

# Serialization
gem 'blueprinter', '~> 1.1'
gem 'oj'

# Pagination
gem 'kaminari', '~> 1.2'

# CORS / security
gem 'rack-cors'
gem 'rack-attack'
gem 'secure_headers'

# Payments
gem 'stripe', '~> 10.0'

# Storage
gem 'aws-sdk-s3', require: false
gem 'image_processing', '~> 1.12'

# QR codes
gem 'rqrcode', '~> 2.2'

# API docs
gem 'rswag-api'
gem 'rswag-ui'

# Logging / observability
gem 'lograge'
gem 'request_store'

# Env
gem 'dotenv-rails'

group :development, :test do
  gem 'rspec-rails', '~> 6.1'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'pry-rails'
  gem 'rubocop',          require: false
  gem 'rubocop-rails',    require: false
  gem 'rubocop-rspec',    require: false
  gem 'rswag-specs'
end

group :test do
  gem 'shoulda-matchers'
  gem 'database_cleaner-active_record'
  gem 'webmock'
  gem 'mock_redis'
  gem 'simplecov', require: false
end

group :development do
  gem 'listen', '~> 3.8'
  gem 'spring'
end
